Ulf Andrae: Monitor updates - Correct syntax for missing data in vfld files - Enable the possibility to give Env_exp files meaningful names   The verobs scripts should now be used as eg.     Run_verobs_all Env_exp_AROME_vs_HIRLAM
git-svn-id: https://svn.hirlam.org/trunk/harmonie/util/monitor@8475 9085bc96-f90c-0410-a38d-ac8cfabbdae3

diff --git a/scr/Clean_ver_js b/scr/Clean_ver_js
--- a/scr/Clean_ver_js
+++ b/scr/Clean_ver_js
@@ -1,23 +1,27 @@
 #!/bin/sh
 
-. ./Env_exp
+#
+# Remove the project defined in Env_exp from WebgraF
+#
+
+if [ $# -eq 1 ] ; then
+   ENV_EXP=$1
+else
+   echo "Please give an Env_exp file"
+   exit 1
+fi
+[[ -s $ENV_EXP ]] || { echo "Please give an existing Env_exp file" ; exit 1 ; }
+
+. $ENV_EXP  || { echo "Could not source $ENV_EXP" ; exit 1 ; }
 
 [[ $WEBCALL == "" ]] && exit
 
-if [ $# -eq 1 ] ; then
-   echo 
-   echo "Remove all plots from $PROJECT/$1"
-   echo
-   $WEBCALL -e $1 -r
-else
-  echo 
-  echo " Removed all plots from $PROJECT"
-  echo 
-  $WEBCALL -r
-fi
+$WEBCALL -r
 
 echo 
-echo " Your new WebgraF content"
+echo " Removed all plots from $PROJECT"
 echo 
+echo 
+echo " Your new WebgraF content:"
 
 $WEBCALL -l
diff --git a/scr/Create_ver_js b/scr/Create_ver_js
--- a/scr/Create_ver_js
+++ b/scr/Create_ver_js
@@ -1,9 +1,24 @@
 #!/bin/sh
 
-set -a
+set -ax
 
-. ./Env_exp
+if [ $# -ge 1 ] ; then
+   ENV_EXP=$1
+      TARG=$2
+else
+   echo "Please give an Env_exp file"
+   exit 1
+fi
+
+[[ -s $ENV_EXP ]] || { echo "Please give an existing Env_exp file" ; exit 1 ; }
+
+. $ENV_EXP  || { echo "Could not source $ENV_EXP" ; exit 1 ; }
 
 [[ $WEBCALL == "" ]] && exit
 
-./Create_ver_js.pl $1
+if [ $TARG = "TEMP" -o $TARG = "SURF" ] ; then
+   ./Create_ver_js.pl $1
+else
+   echo "Please give SURF or TEMP as argument" 
+   exit
+fi
diff --git a/scr/Run_verobs_temp b/scr/Run_verobs_temp
--- a/scr/Run_verobs_temp
+++ b/scr/Run_verobs_temp
@@ -1,17 +1,23 @@
 #!/bin/sh
 
-set -ax
+set -a
 
 #
 # Run verobs for surface variables
 #
 
-# Spec
+if [ $# -eq 1 ] ; then
+   ENV_EXP=$1
+else
+   echo "Please give an Env_exp file"
+   exit 1
+fi
+[[ -s $ENV_EXP ]] || { echo "Please give an existing Env_exp file" ; exit 1 ; }
 
-. ./Env_exp
-
+. $ENV_EXP  || { echo "Could not source $ENV_EXP" ; exit 1 ; }
 
 cd $SCR || exit
+
 DIR=TEMP
 mkdir $WRK/${DIR}_$$ || exit
 
diff --git a/scr/Transport_ver b/scr/Transport_ver
--- a/scr/Transport_ver
+++ b/scr/Transport_ver
@@ -1,13 +1,21 @@
 #!/bin/sh
 
-. ./Env_exp
+if [ $# -eq 1 ] ; then
+   ENV_EXP=$1
+else
+   echo "Please give an Env_exp file"
+   exit 1
+fi
+[[ -s $ENV_EXP ]] || { echo "Please give an existing Env_exp file" ; exit 1 ; }
 
-[[ $WEBCALL == "" ]] && exit
+. $ENV_EXP  || { echo "Could not source $ENV_EXP" ; exit 1 ; }
+[[ $WEBCALL == "" ]] && exit 1
 
 $WEBCALL -x
 
 echo "Your verification results are stored in $PWD/${PROJECT}_export.tar"
 echo "Copy to your local machine, untar and open ${PROJECT}_export/index.html in your browser"
 
-#$WEBCALL -t
-#md5sum ${PROJECT}___transport.tar > ${PROJECT}___transport.tar_md5sum
+$WEBCALL -t
+
+echo "Your verification results are stored in $PWD/${PROJECT}___transport.tar"
