Ulf Andrae: Log plot enhancements - Plot surface analysis increments - Handle odd hours and forecast cycles - Separate entry for CPU plots - Correct softlinks where WebgraF is called
git-svn-id: https://svn.hirlam.org/trunk/harmonie/util/monitor@10935 9085bc96-f90c-0410-a38d-ac8cfabbdae3

diff --git a/scr/Link2file b/scr/Link2file
--- a/scr/Link2file
+++ b/scr/Link2file
@@ -6,13 +6,19 @@
 if [ $# -eq 1 ] ; then
    ENV_EXP=$1
 else
-   echo "Please give an Env_exp file"
+   echo "Please give an Env_exp file or a directory"
    exit 1
 fi
-[[ -s $ENV_EXP ]] || { echo "Please give an existing Env_exp file" ; exit 1 ; }
 
-. $ENV_EXP  || { echo "Could not source $ENV_EXP" ; exit 1 ; }
-[[ $WEBCALL == "" ]] && exit 1
+if [ -d $ENV_EXP ] ; then
+  export WEBGRAF_BASE=$1
+elif [ -s $ENV_EXP ] ; then
+  . $ENV_EXP || { echo "Could not source $ENV_EXP" ; exit 1 ; }
+  [[ $WEBCALL == "" ]] && exit 1
+else
+ echo "Please give an existing Env_exp file" 
+ exit 1
+fi
 
 for F in $( find $WEBGRAF_BASE -type l | grep -v svn ) ; do 
   base=$( dirname $F )
@@ -21,4 +27,3 @@ for F in $( find $WEBGRAF_BASE -type l | grep -v svn ) ; do
   rm -f $F
   cp $base/$FF $F
 done
-
